name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    name: explore-github-actions
    runs-on: ubuntu-latest
    env:
      TEST: WOCCCCCC!!
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - name: My first action
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat
        run: |
          echo This is ${{ env.FIRST_NAME }} ${{ env.LAST_NAME }}

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
        id: random-color-generator
      - name: Get color
        run: |
          echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

      - name: Bash Test
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "$GITHUB_REF"
          echo "${{ github.ref }}"
        shell: bash
        env: 
          TEST: WOCHAO
      
      - name: "Hello world when it's Monday"
        id: print
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
        # if: ${{ jobs.Explore-GitHub-Actions.print.FIRST_NAME == 'Mona' }}
        run: echo "${{ github.event.repository.default_branch }}" 
        